trigger:
  batch: true
  branches:
    include:
    - dev
    - main
  paths:
    include:
    - alerts/**
    exclude:
      - "*"

pool:
  vmImage: ubuntu-latest

variables:
  
  - ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
      - group: OCR_Environment_Var_Prod
      - name: 'App_name'
        value: 'func-notify-prod-westeurope'
      - name: 'Group_name'
        value: 'rg-ocr-prod-westeurope'
  - ${{ if eq(variables['Build.SourceBranchName'], 'dev') }}:
      - group: OCR_Environment_Var
      - name: 'App_name'
        value: 'func-notify-dev-westeurope'
      - name: 'Group_name'
        value: 'rg-ocr-dev-westeurope'

steps:
  - bash: echo "Current branch is $(Build.SourceBranchName)"
  - task: AzureAppServiceSettings@1
    inputs:
      azureSubscription: 'Azure for Students(12c692a0-00e1-447a-8d87-2712018a0472)'
      appName: $(App_name)
      resourceGroupName: $(Group_name)
      appSettings: |
        [
          {
            "name": "DISCORD_WEBHOOK_URL",
            "value": "$(DISCORD_WEBHOOK_URL)"
          },
          {
            "name": "fileblob123_STORAGE",
            "value": "$(fileblob123_STORAGE)"
          },
          {
            "name": "SLACK_WEBHOOK_URL",
            "value": "$(SLACK_WEBHOOK_URL)"
          }
        ]

  - task: AzureFunctionApp@2
    inputs:
      connectedServiceNameARM: 'Azure for Students(12c692a0-00e1-447a-8d87-2712018a0472)'
      appType: 'functionAppLinux'
      appName: $(App_name)
      package: '$(System.DefaultWorkingDirectory)/alerts'
      runtimeStack: 'PYTHON|3.11'

