trigger:
  batch: true
  branches:
    include:
    - dev
    - main
  paths:
    include:
    - alerts/**
    exclude:
      - "*"

pool:
  vmImage: ubuntu-latest

variables:
  - group: OCR_Environment_Var
  - ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
      - name: 'notifyapps'
        value: 'notifyapps_group'
  - ${{ if eq(variables['Build.SourceBranchName'], 'dev') }}:
      - name: 'notifyapps_dev'
        value: 'notifyapps_dev_group'


steps:
  - bash: echo "Current branch is $(Build.SourceBranchName)"
  - task: AzureAppServiceSettings@1
    inputs:
      azureSubscription: 'Azure for Students(12c692a0-00e1-447a-8d87-2712018a0472)'
      appName: $(App_name)
      resourceGroupName: $(Group_name)
      appSettings: |
        [
          {
            "name": "DISCORD_WEBHOOK_URL",
            "value": "$(DISCORD_WEBHOOK_URL)"
          },
          {
            "name": "fileblob123_STORAGE",
            "value": "$(fileblob123_STORAGE)"
          },
          {
            "name": "SLACK_WEBHOOK_URL",
            "value": "$(SLACK_WEBHOOK_URL)"
          }
        ]

  - task: AzureFunctionApp@2
    inputs:
      connectedServiceNameARM: 'Azure for Students(12c692a0-00e1-447a-8d87-2712018a0472)'
      appType: 'functionAppLinux'
      appName: $(App_name)
      package: '$(System.DefaultWorkingDirectory)/alerts'
      runtimeStack: 'PYTHON|3.11'