trigger:
  branches:
    include:
    - main  
  paths:
    include:
    - alerts/**
    - src/**

pool:
  vmImage: ubuntu-latest

jobs:
- job: AlertsJob
  displayName: 'Alerts Handling Job'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/main'), contains(variables['Build.SourceBranch'], 'alerts'))
  steps:
    - template: templates/alerts-job.yml
      parameters:
        azureSubscription: 'Azure for Students(12c692a0-00e1-447a-8d87-2712018a0472)'
        appName: 'notifyapps'
        resourceGroupName: 'notifyapps_group'
        appSettings: |
          [
            {
              "name": "DISCORD_WEBHOOK_URL",
              "value": "$(DISCORD_WEBHOOK_URL)"
            },
            {
              "name": "fileblob123_STORAGE",
              "value": "$(fileblob123_STORAGE)"
            },
            {
              "name": "SLACK_WEBHOOK_URL",
              "value": "$(SLACK_WEBHOOK_URL)"
            }
          ]
        runtimeStack: 'PYTHON|3.11'
        packagePath: '$(System.DefaultWorkingDirectory)/alerts'

- job: SrcJob
  displayName: 'Source Handling Job'
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/main'), contains(variables['Build.SourceBranch'], 'src'))
  steps:
    - template: templates/src-job.yml
      parameters:
        azureSubscription: 'Azure for Students(12c692a0-00e1-447a-8d87-2712018a0472)'
        appName: 'pdfocrjson'
        resourceGroupName: 'pdfocrjson_group'
        appSettings: |
          [
            {
              "name": "STORAGE_CONNECTION_STRING",
              "value": "$(STORAGE_CONNECTION_STRING)"
            },
            {
              "name": "FILE_SHARE_NAME",
              "value": "$(FILE_SHARE_NAME)"
            },
            {
              "name": "BLOB_CONTAINER_NAME",
              "value": "$(BLOB_CONTAINER_NAME)"
            },
            {
              "name": "FORM_RECOGNIZER_ENDPOINT",
              "value": "$(FORM_RECOGNIZER_ENDPOINT)"
            },
            {
              "name": "FORM_RECOGNIZER_API_KEY",
              "value": "$(FORM_RECOGNIZER_API_KEY)"
            }
          ]
        pythonVersion: '3.11'
        script: |
          cd Simple-OCR
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        inlineScript: |
          cd src
          func pack
          func azure functionapp publish $(App_name) --python
